site_name: Zinobe OCRv2

nav:
    - Home: index.md
    - User manual: user_manual.md
    - Developer guide: developer_guide.md
    - Template: template.md
    - Plugin: plugin.md
    - Project OCR: ocr.md

theme: readthedocs

plugins:
    - search
    - mermaid2:
        arguments:
            theme: 'dark'

extra_javascript:
    - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js